Feature/stjs 835 extend scenarios for reactjs app
SecureTrading/py-payments-testing pull request #121
Opened 2020-08-20 13:57 UTC by tkusiakpgs

2020-08-20 14:36 UTC, ngrzegorzewicz approved these changes

2020-08-24 05:58 UTC, msakowicz requested changes

2020-08-24 05:58 UTC, msakowicz commented on features/e2e_tests/e2e_card_payment_with_request_types.feature
> +    Given JS library is configured with VISA_CHECKOUT_WITH_REQUEST_TYPES_CONFIG and BASE_JWT
Why VISA_CHECKOUT_WITH_REQUEST_TYPES_CONFIG if in scenario you use card payments method?

2020-08-24 05:58 UTC, msakowicz commented on features/e2e_tests/e2e_card_payments_tests.feature
> +    When User fills payment form with defined card VISA_NON_FRICTIONLESS
If you are using VISA_NON_FRICTIONLESS you should also add step for confirm cardinal authentication popup

2020-08-24 08:46 UTC, msakowicz approved these changes

2020-08-24 09:21 UTC, merged